request_parser:
  next: add_meta
  sidecars:
    - access_logger
  config:
    discard_headers:
      - host
      - content-length

add_meta:
  next: downloader
  config:
    name: foo
    data: "#msg.request().headers()"
    evaluated: true

downloader:
  next: out_beautifier
  config:
    discard_headers:
      - "content-length"

out_beautifier:
  next: send_back
  config:
    mode: json

send_back:
  sidecars:
    - generic_logger
    - file_appender_serializer

file_appender_serializer:
  config:
    filename: foobar.txt

generic_logger:
  config:
    data: "#msg.meta()"
    evaluated: true

access_logger:
  config: {}