request:
  next: transform_headers
  sidecars:
    - access_logger
  config:
    discard_headers:
      - host
      - content-length

transform_headers:
  next: upstream_http
  config:
    add:
      - name: x-original-remoteIP
        value: "#msg.request().remoteIP()"
        evaluated: true
    set:
      - name: user-agent
        value: "#msg.request().getHeader('user-agent')+' - Afthem'"
        evaluated: true

upstream_http:
  next: out_beautifier
  config:
    discard_headers:
      - "content-length"

out_beautifier:
  next: send_back
  config:
    mode: json

send_back:
  sidecars:
    - access_logger
    - file_appender_serializer

file_appender_serializer:
  config:
    filename: log/serialized.log

access_logger:
  config: {}