proxy/request:
  next: transformer/transform_headers
  sidecars:
    - sidecar/access_logger
  config:
    discard_headers:
      - host
      - content-length

transformer/transform_headers:
  next: proxy/upstream_http
  config:
    add:
      - name: x-original-remoteIP
        value: "#msg.request().remoteIP()"
        evaluated: true
    set:
      - name: user-agent
        value: "#msg.request().getHeader('user-agent')+' - Afthem'"
        evaluated: true

proxy/upstream_http:
  next: transformer/out_beautifier
  config:
    discard_headers:
      - "content-length"

transformer/out_beautifier:
  next: proxy/send_back
  config:
    mode: json

proxy/send_back:
  sidecars:
    - sidecar/access_logger
    - sidecar/file_appender_serializer

sidecar/file_appender_serializer:
  config:
    filename: log/serialized.log

sidecar/access_logger:
  config: {}