request_parser:
  next: transform_headers
  sidecars:
    - access_logger
  config:
    discard_headers:
      - host
      - content-length

transform_headers:
  next: downloader
  config:
    add_headers:
      - name: x-foo
        value: bar
      - name: user-agent
        value: "#msg.request().getHeader('user-agent')+' - Foo Agent'"
        evaluated: true

downloader:
  next: out_beautifier
  config:
    discard_headers:
      - "content-length"

out_beautifier:
  next: send_back
  config:
    mode: json

send_back:
  sidecars:
    - access_logger
    - file_appender_serializer

file_appender_serializer:
  config:
    filename: log/foobar.txt

access_logger:
  config: {}