proxy/request:
  next: transformer/add_meta
  sidecars:
    - sidecar/access_logger

transformer/add_meta:
  next: proxy/upstream_http
  config:
    name: foobar
    value: "#msg.request().getHeader('accept')"
    evaluated: true

proxy/upstream_http:
  next: proxy/send_back

proxy/send_back:
  sidecars:
  - sidecar/generic_logger

sidecar/generic_logger:
  config:
    value: "#msg.meta().get('foobar')"
    evaluated: true